# Remote Console Config

# Address to listen on, leave blank for all
address: ''

# Port to bind to:
port: 8765

# Main connection password, must be defined
password: 'walrus'

# List of admins / IPs that don't have to use the password, should have avoided use
admins:

